[app]
port="8003"

[database]
host="postgres"
name="microservices_domain"
username="ralph"
password="Letmein12@"
port="5432"
sslmode="disable"

[jwt]
secret="THISISSECRETKEYDONTGIVEITAWAY"
hourLifeSpan=24