[app]
port="8002"

[database]
host="postgres"
name="microservices_users"
username="ralph"
password="Letmein12@"
port="5432"
sslmode="disable"

[jwt]
secret="THISISSECRETKEYDONTGIVEITAWAY"
hourLifeSpan=24